Change the README for a better Getting Start
the-open-agent/openagent pull request #136
Opened 2021-02-09 06:36 UTC by yuqing521

I tried to adjust the structure of the original readme so that beginners can better try the project

2021-02-10 10:20 UTC, kocoler commented
This makes the README more detailed!
LGTM

2021-02-10 10:21 UTC, kocoler approved these changes

2021-02-10 14:39 UTC, RobotHuang requested changes

2021-02-10 14:39 UTC, RobotHuang commented on README.md
> +    form github
`from github`, not `form`

2021-02-10 14:39 UTC, RobotHuang commented on README.md
> +        And to improve security, you could set a `state` value determined by **yourself** to make sure the request is requesting by yourself, such as "random".
maybe `requested by yourself`?

2021-02-10 14:39 UTC, RobotHuang commented on README.md
> +        You may also have to fill in the **same** information at: https://github.com/casbin/casbin-forum/blob/master/web/src/Conf.js. By the way, you could change the value of `scope` to get differen
`from them`

2021-02-13 16:19 UTC, yuqing521 commented
Thanks for helping correct the mistake

2021-03-20 11:11 UTC, closed without merging