feat: add user rich rank list page
the-open-agent/openagent pull request #157
Opened 2021-02-28 16:00 UTC by oceanlvr

fix: #132 

add API:

* getMemberRichList, get the top of 15 rich users.

![image](https://user-images.githubusercontent.com/36698124/109424918-ed143a00-7a20-11eb-9ae5-03dd0f7e7758.png)

Signed-off-by: oceanlvr <657531018@qq.com>

2021-03-01 12:55 UTC, oceanlvr commented
@hsluoyz please review:) thanks!

2021-03-01 13:35 UTC, hsluoyz requested changes

2021-03-01 13:35 UTC, hsluoyz commented on routers/router.go
> +	beego.Router("/api/get-members-rankRich", &controllers.APIController{}, "GET:GetMembersRankRich")
/api/get-ranking-rich

2021-03-01 13:35 UTC, hsluoyz commented on web/src/App.js
> +import RichBox from "./main/RichBox";
RankingRichBox

2021-03-01 13:35 UTC, hsluoyz commented on web/src/locales/en.json
> +    "Rich rank": "rich rank",
"Rich ranking": "Rich ranking",

2021-03-01 13:35 UTC, hsluoyz commented on object/member.go
> +func GetMembersRankRich() []*Member {
GetRankingRich

2021-03-01 15:30 UTC, hsluoyz requested changes

2021-03-01 15:30 UTC, hsluoyz commented on web/src/backend/MemberBackend.js
> +export function getMemberRichList() {
getRankingRichList

2021-03-01 15:30 UTC, hsluoyz commented on web/src/main/RankingRichBox.js
> +  renderRichList() {
render()

2021-03-02 02:14 UTC, hsluoyz approved these changes

2021-03-02 02:14 UTC, merged