feat: Add new member in UI #194
the-open-agent/openagent pull request #242
Opened 2021-05-26 12:57 UTC by oranges-eating

Signed-off-by: killer <1533063601@qq.com>

2021-05-26 13:02 UTC, oranges-eating commented
https://user-images.githubusercontent.com/53165082/119664094-92467f00-be65-11eb-881b-87d47d4aef40.mp4

2021-05-26 13:04 UTC, hsluoyz commented
@kocoler @Kininaru plz review.

2021-05-26 13:18 UTC, Kininaru requested changes

2021-05-26 13:18 UTC, Kininaru commented on web/src/main/NewMember.js
> +import React from "react";
Casbin license.

2021-05-26 13:18 UTC, Kininaru commented on web/src/main/NewMember.js
> +    componentDidMount() {
This is an empty function.

2021-05-26 13:18 UTC, Kininaru commented on controllers/member.go
> -
No need to remove this. You can set your Go style like this: 

![image](https://user-images.githubusercontent.com/42638489/119666288-d5095680-be67-11eb-9701-df31fa754dcf.png)

2021-05-26 14:35 UTC, kocoler commented on controllers/member.go
> +		resp = Response{Status: "fail", Msg: "Unauthorized."}
Msg wrong.

2021-05-26 14:35 UTC, kocoler commented on controllers/member.go
> +	if object.AddMember(&member) {
Missing `UploadAvatarToOSS`.

2021-05-27 06:04 UTC, kocoler approved these changes

2021-05-27 06:05 UTC, Kininaru approved these changes

2021-05-27 06:19 UTC, hsluoyz commented
@oranges-eating plz provide a demo site and set my name as an admin.

2021-05-28 12:13 UTC, oranges-eating commented
@hsluoyz https://forum.oranges.chromium.link/ 
usename:hsluoyz password:123

2021-05-28 16:39 UTC, merged