fix: Fix the debug warnings in browser console #269
the-open-agent/openagent pull request #274
Opened 2021-06-13 10:44 UTC by oranges-eating

Signed-off-by: killer <1533063601@qq.com>

2021-06-13 12:55 UTC, hsluoyz commented
@kocoler @Kininaru

2021-06-13 13:14 UTC, Kininaru requested changes

2021-06-13 13:14 UTC, keainye commented on web/public/index.html
> -    <link rel="apple-touch-icon" href="%PUBLIC_URL%/logo192.png" />
I think here we should replace `%PUBLIC_URL%` with a valid src url instead of removing it.

2021-06-13 13:14 UTC, Kininaru commented on web/public/manifest.json
> -      "sizes": "512x512"
Same reason as `index.html`.

2021-06-13 13:14 UTC, Kininaru commented on web/src/main/MemberBox.js
> +                      onClick={this.block()}
Parameter `memberId` missed.

2021-06-13 13:14 UTC, Kininaru commented on web/src/main/NodeBox.js
> +                  href="#"
We can remove these void codes.

2021-06-13 13:14 UTC, Kininaru commented on web/src/main/TopicBox.js
> +  ignoretopic() {}
`ignoreTopic`

2021-06-13 13:14 UTC, Kininaru commented on web/src/main/TopicBox.js
> +  openshare() {}
openShare

2021-06-13 13:14 UTC, Kininaru commented on web/src/rightbar/RightAccountBox.js
> -                  </Link>
Link should not be removed.

2021-06-13 13:57 UTC, Kininaru approved these changes

2021-06-13 14:16 UTC, kocoler approved these changes

2021-06-14 02:22 UTC, oranges-eating commented
@hsluoyz Is there any problem with this？

2021-06-14 03:02 UTC, merged