add check node info on add new topic and reply
the-open-agent/openagent pull request #313
Opened 2021-06-25 03:29 UTC by arthur-jx

2021-06-25 04:36 UTC, hsluoyz commented
@arthur-jx fix:

![image](https://user-images.githubusercontent.com/3787410/123370283-fc138f00-d5b1-11eb-9c41-5e5b60d39962.png)

2021-06-25 04:37 UTC, hsluoyz commented
@arthur-jx what's this for?

2021-06-25 04:37 UTC, hsluoyz commented
@kocoler @Kininaru plz review.

2021-06-25 05:19 UTC, Kininaru requested changes

2021-06-25 05:19 UTC, Kininaru commented on object/mailing_list.go
> +func (r Reply) AddReplyToMailingList(title string, targetNode *Node) {
We'd better transfer `targetTopic` here. We may use some of its member variables in the future.

2021-06-25 05:20 UTC, Kininaru commented on object/mailing_list.go
> +func (r Reply) AddReplyToMailingList(title string, targetNode *Node) {
And please resolve the failed checks.

2021-06-25 05:22 UTC, Kininaru commented
> @arthur-jx what's this for?

This PR is to make sure that the father topic of a new reply exists and the father node of a new topic exists.

2021-06-29 10:29 UTC, closed without merging

2021-06-30 01:45 UTC, arthur-jx commented
This is an obvious bug, why not accept my fix?

2021-06-30 10:48 UTC, hsluoyz commented
@arthur-jx this is because the code quality of this PR is below the bar. You can send GitHub issue and we will assign community members to make PR.

2021-07-01 02:17 UTC, arthur-jx commented
@hsluoyz  Since the code quality of current community members is so high, why are there so many low-level bugs?

2021-07-01 06:16 UTC, hsluoyz commented
@arthur-jx which ones? you can friendly point out the low-level bugs, we will fix them one by one.