fix: replace web auth with casdoor-js-sdk
the-open-agent/openagent pull request #339
Opened 2021-07-29 16:03 UTC by WindSpiritSR

Fixed: #338 

Deployed at: https://forum.leviatan.cn/

Signed-off-by: WindSpiritSR <simon343riley@gmail.com>

2021-08-05 13:23 UTC, hsluoyz commented
@kocoler @Kininaru

2021-08-06 13:40 UTC, kocoler approved these changes

2021-08-06 15:23 UTC, hsluoyz requested changes
@WindSpiritSR You should replace all the Auth files with SDK:

![image](https://user-images.githubusercontent.com/3787410/128533943-a129c648-4925-447e-8fd6-94fd4d6f72cc.png)

2021-08-07 15:12 UTC, hsluoyz requested changes

2021-08-07 15:12 UTC, hsluoyz commented on web/src/Conf.js
> +  casnodeUrl: "http://localhost:7000",
`casnodeUrl` is used nowhere.

2021-08-07 15:12 UTC, hsluoyz commented on web/src/main/FilesBox.js
>  import * as Setting from "../Setting";
Setting is already imported

2021-08-07 15:12 UTC, hsluoyz commented on web/src/main/NewBox.js
>  import * as Setting from "../Setting";
Setting is already imported

2021-08-07 15:12 UTC, hsluoyz commented on web/src/main/NodeBox.js
>  import * as Setting from "../Setting";
Setting is already imported

2021-08-07 15:12 UTC, hsluoyz commented on web/src/main/SignoutBox.js
> +import * as Setting from "../Setting";
Setting is already imported

2021-08-07 15:12 UTC, hsluoyz commented on web/src/rightbar/RightSigninBox.js
> +import * as Setting from "../Setting";
Setting is already imported

2021-08-07 15:12 UTC, hsluoyz commented on web/src/Header.js
>  import * as Conf from "./Conf";
Setting is already imported

2021-08-07 15:12 UTC, hsluoyz commented on web/src/AuthCallback.js
> +import * as Setting from "./Setting";
Setting is already imported

2021-08-07 15:12 UTC, hsluoyz commented on web/package.json
> +    "casdoor-js-sdk": "0.0.1",
yarn.lock?

2021-08-08 02:01 UTC, hsluoyz requested changes

2021-08-08 02:01 UTC, hsluoyz commented on web/yarn.lock
> +  resolved "https://registry.nlark.com/casdoor-js-sdk/download/casdoor-js-sdk-0.0.2.tgz#253cea3f7316f9cbb3fbda01d2bf0b94c3fc8508"
Use: `registry.yarnpkg.com`

2021-08-08 02:01 UTC, hsluoyz commented on web/src/Setting.js
> +export function getSigninUrl(redirectUrl) {
No arg for `getSigninUrl()`

2021-08-08 12:41 UTC, hsluoyz approved these changes

2021-08-08 12:41 UTC, merged