feat: Add subscribe
the-open-agent/openagent pull request #457
Opened 2022-04-03 12:47 UTC by Nekotoxin

Done:
1. extend the favorite type from 3 types to 5 types
![image](https://user-images.githubusercontent.com/75596353/161428563-73215929-6f0a-4280-8cd0-94abe1d6a045.png)
2. add the topic subscribe feature
![image](https://user-images.githubusercontent.com/75596353/161428631-b63ae053-b80e-4612-9220-d679c2db33a5.png)
3. change the favor to focus(contain favor and subscribe)
![image](https://user-images.githubusercontent.com/75596353/161428653-4c537909-dff8-41b8-8cb6-0c548ddbdc62.png)
4. new /my/topic page
![image](https://user-images.githubusercontent.com/75596353/161428715-d9fb0d0d-523b-467f-80a9-687a3c510e62.png)
5. reply to a topic will automatically add the topic to subscribe list,and when the topic update again, you will get email notification.
Todo:
add the subscribe feature for single reply.

2022-04-04 09:08 UTC, Nekotoxin commented
![image](https://user-images.githubusercontent.com/75596353/161511751-643e2d9e-a06c-46bc-ba0f-ef0ec8f97801.png)

2022-04-04 09:17 UTC, Nekotoxin commented
1.
![image](https://user-images.githubusercontent.com/75596353/161513229-14dae46e-09ec-4112-8a28-a1980c72e018.png)
change the favoritesType from int to string
2.
improve the translation

2022-04-04 16:05 UTC, hsluoyz requested changes

2022-04-04 16:05 UTC, hsluoyz commented on controllers/favorites.go
> +		resp = Response{Status: "fail", Msg: "param wrong"}
Use `ResponseOk` and `ResponseError` in all possible places.

2022-04-04 16:05 UTC, hsluoyz commented on controllers/reply.go
> +//@Tag Reply API
space

2022-04-04 16:05 UTC, hsluoyz commented on web/src/main/NewReplyBox.js
> +    FavoritesBackend.addFavorites(this.state.topicId, "subscribe_topic").then((res) => {
new line

2022-04-05 00:47 UTC, hsluoyz approved these changes

2022-04-05 00:47 UTC, merged