fix: componentWillReceiveProps api and key in jsx
the-open-agent/openagent pull request #551
Opened 2022-10-01 05:25 UTC by kcfuler

2022-10-01 07:17 UTC, hsluoyz requested changes

2022-10-01 07:17 UTC, hsluoyz commented on conf/app.conf
> +dataSourceName = root:admin123@tcp(localhost:3306)/
don't change this

2022-10-01 07:26 UTC, kcfuler commented on conf/app.conf
> +dataSourceName = root:admin123@tcp(localhost:3306)/
ok i revert it back

2022-10-02 01:59 UTC, hsluoyz approved these changes

2022-10-02 02:13 UTC, merged