feat: update antd to v5.2.3
the-open-agent/openagent pull request #586
Opened 2023-07-18 18:44 UTC by kv-chiu

2023-07-20 15:43 UTC, hsluoyz requested changes

2023-07-20 15:43 UTC, hsluoyz commented on web/src/App.js
> +import {Content} from "antd/es/layout/layout";
Not this, see official example

2023-07-20 15:43 UTC, hsluoyz commented on web/src/App.js
> +      <Dropdown key="/rightDropDown" overlay={menu} className="rightdropdown">
Why change to `rightdropdown`?

2023-07-20 15:43 UTC, hsluoyz commented on web/src/App.less
> +.app-logo {
Why change these?

2023-07-20 15:43 UTC, hsluoyz commented on web/src/Conf.js
> +  colorPrimary: "#5734d3",
Does this work?

2023-07-20 15:43 UTC, hsluoyz commented on web/src/FileTree.js
> +  Button,
Don't do this

2023-07-20 19:40 UTC, kv-chiu commented
https://github.com/casbin/casibase/assets/132759132/096ab338-759f-41e3-bd72-1951d08d10c3

2023-07-20 19:45 UTC, kv-chiu commented
https://github.com/casbin/casibase/assets/132759132/4b8f67b6-f876-4397-8890-8a5540f44172

2023-07-21 05:04 UTC, hsluoyz approved these changes

2023-07-21 05:04 UTC, merged