feat: Casdoor storage API
the-open-agent/openagent pull request #594
Opened 2023-07-22 10:11 UTC by WinterOfBit

solved #584 

added abstract [storage.go](https://github.com/WinterOfBit/casibase/blob/feature/storage/storage/storage.go) and impl casdoor.go

tested using [storage_test#TestCasdoor()](https://github.com/WinterOfBit/casibase/blob/8c0ae44eaf963f82fa9fc85c192a1584263fc1c5/storage/storage_test.go#L35)

2023-07-22 10:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/casbin/casibase?pullRequest=594) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/casbin/casibase?pullRequest=594) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/casbin/casibase?pullRequest=594) it.</sub>

2023-07-22 10:50 UTC, hsluoyz commented
@WinterOfBit plz fix linter and CLA:

![image](https://github.com/casbin/casibase/assets/3787410/3f9fecf3-70f7-4b8f-a0f3-65e4292e57a0)

2023-07-22 14:02 UTC, WinterOfBit commented
> @WinterOfBit plz fix linter and CLA:
> 
> ![image](https://user-images.githubusercontent.com/3787410/255325525-3f9fecf3-70f7-4b8f-a0f3-65e4292e57a0.png)

fixed

2023-07-22 14:41 UTC, hsluoyz requested changes
Also demo video for non-aliyun provider?

2023-07-22 14:41 UTC, hsluoyz commented on storage/casdoor.go
> +			beego.AppConfig.String("casdoorOrganization"),
Define some shared global variables, don't use `beego.AppConfig.String("xxx")` so many times

2023-07-22 14:41 UTC, hsluoyz commented on storage/storage.go
> +func NewStorageProvider(provider string) Storage {
Is it possible to select different Casdoor providers to use for each Casibase store? A provider name will be specified in the store edit page

2023-07-23 18:37 UTC, WinterOfBit commented
> Also demo video for non-aliyun provider?

working on frontend impl

2023-07-29 06:15 UTC, hsluoyz commented
@WinterOfBit hi, any update?

2023-07-29 11:23 UTC, hsluoyz approved these changes

2023-07-29 11:24 UTC, merged

2023-07-31 13:25 UTC, wintbiit commented
> @WinterOfBit hi, any update?

@hsluoyz Being busy for some days. I'll make another pr later to make this func more perfect.

2023-07-31 14:10 UTC, hsluoyz commented
@WinterOfBit the whole task has been finished already :) no need to worry now

2023-07-31 15:32 UTC, WinterOfBit commented
> @WinterOfBit the whole task has been finished already :) no need to worry now

@hsluoyz ok. Glad to see that!