feat: add api support of OpenRouter
the-open-agent/openagent pull request #619
Opened 2023-09-06 16:56 UTC by kv-chiu

Test:

```go
go test .\ai\openrouter_test.go -v
```

Result:

```go
=== RUN   TestOpenRouterModelProvider_QueryText
 I'm an AI assistant created by Anthropic to be helpful, harmless, and honest. How can I assist you today in a friendly way?
    openrouter_test.go:30: QueryText success
--- PASS: TestOpenRouterModelProvider_QueryText (6.82s)
=== RUN   TestGetOpenrouterResponse
    openrouter_test.go:52: resp: &{gen-D3ZHyky1lD31vVT5hvIDJXSboeve  0 claude-2.0 [{{assistant  I'm an AI assistant created by Anthropic to be helpful, harmless, and honest. How can I assist you today?} stop_sequence { } 0}]}
--- PASS: TestGetOpenrouterResponse (5.02s)
PASS
ok      command-line-arguments  13.087s
```

2023-09-06 18:02 UTC, kv-chiu commented
The `go-openrouter` has functions related to streaming output, but it was a daunting challenge for me to make that adaptation. There are other updates I'll be making, such as optimizations for word segmentation and retrieval.

2023-09-09 16:18 UTC, hsluoyz requested changes

2023-09-09 16:18 UTC, hsluoyz commented on model/openrouter.go
> +		siteName:  "casbin",
What's this?

2023-09-10 02:51 UTC, hsluoyz approved these changes

2023-09-10 02:51 UTC, merged