feat: files could copy into chat input box
the-open-agent/openagent pull request #802
Opened 2024-05-06 09:38 UTC by Sherlocksuper

Fix: #801 

https://github.com/casibase/casibase/assets/116318567/57b0d4a3-27c3-4984-b968-e2c4bc29ba96

2024-05-07 07:44 UTC, hsluoyz requested changes

2024-05-07 07:44 UTC, hsluoyz commented on web/src/ChatBox.js
> +    const date = new Date();
Use moment to format date, don't do it yourself

![image](https://github.com/casibase/casibase/assets/3787410/30ea6568-c75a-48e2-b835-e66d8d5bf23c)

2024-05-07 07:44 UTC, hsluoyz commented on web/src/ChatBox.js
> +      fileName = this.props.name + "_" + dateString + "." + this.inputImage.files[0].name.split(".")[this.inputImage.files[0].name.split(".").length - 1];
Don't change if it has filename

2024-05-07 07:44 UTC, hsluoyz commented on web/src/ChatPage.js
> +          <ChatBox disableInput={this.state.disableInput} messages={this.state.messages} sendMessage={(text, fileName) => {this.sendMessage(text, fileName, false);}} account={this.props.account} name
chatName={this.state.chat?.name}

2024-05-07 07:44 UTC, hsluoyz commented on web/src/ChatBox.js
> +                              const scaledWidth = Math.round(originalWidth * Ratio);
What's this scaling code?

2024-05-07 07:44 UTC, hsluoyz commented on web/src/ChatBox.js
> +    this.inputImage.value = "";
What's this?

2024-05-07 10:07 UTC, hsluoyz requested changes

2024-05-07 10:07 UTC, hsluoyz commented on web/src/ChatBox.js
> +    this.targetFileName = null;
Why add this?

2024-05-07 10:07 UTC, hsluoyz commented on web/src/ChatBox.js
> +    if (this.targetFileName) {
What's this used for?

2024-05-07 10:07 UTC, hsluoyz commented on web/src/ChatBox.js
> +                            const scaledWidth = Math.round(originalWidth * Ratio);
What's this?

2024-05-07 11:45 UTC, Sherlocksuper commented on web/src/ChatBox.js
> +    this.targetFileName = null;
input 无法人为设置除空以外的变量，所以需要有一个变量来保存“复制操作”输入的变量名

2024-05-07 12:22 UTC, Sherlocksuper commented on web/src/ChatBox.js
> +                              const scaledWidth = Math.round(originalWidth * Ratio);
To ensure consistency with the original handleInputChange logic

2024-05-07 12:26 UTC, Sherlocksuper commented on web/src/ChatBox.js
> +                            const scaledWidth = Math.round(originalWidth * Ratio);
To ensure consistency with the original handleInputChange logic

2024-05-08 12:30 UTC, hsluoyz approved these changes

2024-05-08 12:30 UTC, merged