add a new model stepfun to casibase #819
the-open-agent/openagent pull request #971
Opened 2024-12-06 09:24 UTC by stardustlove

2024-12-06 09:34 UTC, stardustlove commented
feat: add Stepfun Model Provider to Casibase #819

2024-12-07 00:16 UTC, hsluoyz requested changes

2024-12-07 00:16 UTC, hsluoyz commented on model/stepfun.go
> +	url := "https://api.stepfun.com/v1/token/count"
Why call another API to calculate tokens? Their docs (https://platform.stepfun.com/docs/pricing/intro) said, they already returned the token usage in the response?

![image](https://github.com/user-attachments/assets/cb0c553f-1e32-459d-b743-db6a255c4b76)

2024-12-07 00:16 UTC, hsluoyz commented on web/src/Setting.js
> +  } else if (type === "StepFun") {
Put before Dummy

2024-12-07 03:17 UTC, hsluoyz commented
@stardustlove resolve the conflicts

![image](https://github.com/user-attachments/assets/ed84d942-7108-4938-9e4e-82f5aea4e4fd)

2024-12-07 12:31 UTC, hsluoyz approved these changes

2024-12-07 13:29 UTC, merged